name: jalan_aman
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^0.69.0
  flutter_map: ^7.0.1
  flutter_map_marker_popup: ^7.0.0
  latlong2: ^0.9.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  image_picker: ^1.1.1
  path: ^1.9.0
  mime: ^1.0.5
  dio: ^5.9.0
  geolocator: ^10.1.0
  socket_io_client: ^3.0.0
  audioplayers: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/sounds/notification.mp3